import Foundation

enum VehicleLightCoverage {
    static func name(_ value: UInt64) -> String {
        switch value {
        case 0: return L10n.text("Unspecified")
        case 1: return L10n.text("Brake light left")
        case 2: return L10n.text("Brake light center")
        case 3: return L10n.text("Brake light right")
        case 4: return L10n.text("Position light front left")
        case 5: return L10n.text("Position light front right")
        case 6: return L10n.text("Position light rear left")
        case 7: return L10n.text("Position light rear right")
        case 8: return L10n.text("High beam left")
        case 9: return L10n.text("High beam right")
        case 10: return L10n.text("Low beam left")
        case 11: return L10n.text("Low beam right")
        case 12: return L10n.text("Daytime running light left")
        case 13: return L10n.text("Daytime running light right")
        case 14: return L10n.text("Turn indicator front left")
        case 15: return L10n.text("Turn indicator front right")
        case 16: return L10n.text("Turn indicator rear left")
        case 17: return L10n.text("Turn indicator rear right")
        case 18: return L10n.text("Registration plate")
        case 19: return L10n.text("Fog light front any")
        case 20: return L10n.text("Fog light rear any")
        case 21: return L10n.text("Side mark lights")
        case 22: return L10n.text("Low beam any")
        case 23: return L10n.text("High beam any")
        case 24: return L10n.text("Position any")
        case 25: return L10n.text("Daytime running light any")
        case 26: return L10n.text("Brake light any")
        case 27: return L10n.text("Turn indicator left any")
        case 28: return L10n.text("Turn indicator right any")
        case 29: return L10n.text("Fog light rear left")
        case 30: return L10n.text("Fog light rear right")
        case 31: return L10n.text("Cornering light left")
        case 32: return L10n.text("Cornering light right")
        case 33: return L10n.text("Front side marker left")
        case 34: return L10n.text("Front side marker right")
        case 35: return L10n.text("Reverse left")
        case 36: return L10n.text("Reverse right")
        case 37: return L10n.text("Turn indicator side left")
        case 38: return L10n.text("Turn indicator side right")
        case 39: return L10n.text("Concealable headlamp left")
        case 40: return L10n.text("Concealable headlamp right")
        default: return L10n.format("Unknown (%d)", Int(clamping: value))
        }
    }

    // Health.LightWarnings fields, distinct from MyCars LightWarning enum values.
    static func healthName(_ field: Int) -> String? {
        switch field {
        case 22: return L10n.text("Brake light any")
        case 21: return L10n.text("Brake light center")
        case 19: return L10n.text("Brake light left")
        case 20: return L10n.text("Brake light right")
        case 39: return L10n.text("Concealable headlamp left")
        case 40: return L10n.text("Concealable headlamp right")
        case 41: return L10n.text("Cornering light left")
        case 42: return L10n.text("Cornering light right")
        case 31: return L10n.text("Daytime running light any")
        case 29: return L10n.text("Daytime running light left")
        case 30: return L10n.text("Daytime running light right")
        case 17: return L10n.text("Fog light front")
        case 18: return L10n.text("Fog light rear")
        case 15: return L10n.text("Fog light rear left")
        case 16: return L10n.text("Fog light rear right")
        case 14: return L10n.text("High beam any")
        case 12: return L10n.text("High beam left")
        case 13: return L10n.text("High beam right")
        case 11: return L10n.text("Low beam any")
        case 9: return L10n.text("Low beam left")
        case 10: return L10n.text("Low beam right")
        case 27: return L10n.text("Position light front")
        case 23: return L10n.text("Position light front left")
        case 24: return L10n.text("Position light front right")
        case 28: return L10n.text("Position light rear")
        case 25: return L10n.text("Position light rear left")
        case 26: return L10n.text("Position light rear right")
        case 32: return L10n.text("Registration plate light")
        case 38: return L10n.text("Reverse light any")
        case 36: return L10n.text("Reverse light left")
        case 37: return L10n.text("Reverse light right")
        case 35: return L10n.text("Side marker light any")
        case 33: return L10n.text("Side marker light left")
        case 34: return L10n.text("Side marker light right")
        case 1: return L10n.text("Turn indicator front left")
        case 2: return L10n.text("Turn indicator front right")
        case 5: return L10n.text("Turn indicator left")
        case 3: return L10n.text("Turn indicator rear left")
        case 4: return L10n.text("Turn indicator rear right")
        case 6: return L10n.text("Turn indicator right")
        case 7: return L10n.text("Turn indicator side left")
        case 8: return L10n.text("Turn indicator side right")
        default: return nil
        }
    }
}
