#!/bin/sh
set -eu

# Script to inject obfuscated Volvo API credentials at build time without committing secrets to git.
# Reads credentials from environment variables or .env.secrets / .env.local

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS_FILE="$ROOT_DIR/.env.secrets"
LOCAL_ENV_FILE="$ROOT_DIR/.env.local"
OUTPUT_SWIFT="$ROOT_DIR/Sources/Hisingen/Services/API/GeneratedVolvoSecrets.swift"

# Load from file if env vars not already set
if [ -f "$SECRETS_FILE" ]; then
    # shellcheck disable=SC1090
    . "$SECRETS_FILE"
elif [ -f "$LOCAL_ENV_FILE" ]; then
    # shellcheck disable=SC1090
    . "$LOCAL_ENV_FILE"
fi

CLIENT_ID="${VOLVO_CLIENT_ID:-}"
CLIENT_SECRET="${VOLVO_CLIENT_SECRET:-}"
VCC_API_KEY="${VOLVO_VCC_API_KEY:-}"

if [ -n "$CLIENT_ID" ] && [ -n "$CLIENT_SECRET" ] && [ -n "$VCC_API_KEY" ]; then
    echo "🔒 Injecting obfuscated Volvo Developer credentials..."

    python3 - <<EOF
import os

client_id = """$CLIENT_ID""".strip()
client_secret = """$CLIENT_SECRET""".strip()
vcc_api_key = """$VCC_API_KEY""".strip()

mask_key = 0x5C

def obfuscate(s):
    b = s.encode('utf-8')
    masked = [x ^ mask_key for x in b]
    return ', '.join(f"0x{x:02X}" for x in masked)

output = f"""// Generated by Scripts/inject-secrets.sh - DO NOT EDIT MANUALLY OR COMMIT REAL SECRETS
import Foundation

enum GeneratedVolvoSecrets {{
    static let isConfigured: Bool = true

    static var clientID: String {{
        let key: UInt8 = 0x{mask_key:02X}
        let bytes: [UInt8] = [{obfuscate(client_id)}]
        return String(bytes: bytes.map {{ \$0 ^ key }}, encoding: .utf8) ?? ""
    }}

    static var clientSecret: String {{
        let key: UInt8 = 0x{mask_key:02X}
        let bytes: [UInt8] = [{obfuscate(client_secret)}]
        return String(bytes: bytes.map {{ \$0 ^ key }}, encoding: .utf8) ?? ""
    }}

    static var vccApiKey: String {{
        let key: UInt8 = 0x{mask_key:02X}
        let bytes: [UInt8] = [{obfuscate(vcc_api_key)}]
        return String(bytes: bytes.map {{ \$0 ^ key }}, encoding: .utf8) ?? ""
    }}
}}
"""

with open("$OUTPUT_SWIFT", "w") as f:
    f.write(output)

print("✅ Obfuscated credentials generated into Sources/Hisingen/Services/API/GeneratedVolvoSecrets.swift")
EOF
else
    # Generate clean placeholder struct if no secrets provided
    cat <<EOF > "$OUTPUT_SWIFT"
// Default public fallback with no embedded secrets
import Foundation

enum GeneratedVolvoSecrets {
    static let isConfigured: Bool = false
    static var clientID: String { "" }
    static var clientSecret: String { "" }
    static var vccApiKey: String { "" }
}
EOF
    echo "ℹ️ No Volvo developer secrets found in environment or .env.secrets — using empty default template."
fi
