#!/bin/sh
set -eu

# Script to inject obfuscated Volvo API credentials at build time without committing secrets to git.
# Reads credentials from environment variables or .env.secrets / .env.local

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
SECRETS_FILE="$ROOT_DIR/.env.secrets"
LOCAL_ENV_FILE="$ROOT_DIR/.env.local"
OUTPUT_SWIFT="$ROOT_DIR/Sources/Hisingen/Services/API/GeneratedVolvoSecrets.swift"
POLESTAR_OUTPUT_SWIFT="$ROOT_DIR/Sources/Hisingen/Services/API/GeneratedPolestarSecrets.swift"

# Load from file if env vars not already set
if [ -f "$SECRETS_FILE" ]; then
    # shellcheck disable=SC1090
    . "$SECRETS_FILE"
elif [ -f "$LOCAL_ENV_FILE" ]; then
    # shellcheck disable=SC1090
    . "$LOCAL_ENV_FILE"
fi

CLIENT_ID="${VOLVO_CLIENT_ID:-}"
CLIENT_SECRET="${VOLVO_CLIENT_SECRET:-}"
VCC_API_KEY="${VOLVO_VCC_API_KEY:-}"

if [ -n "$CLIENT_ID" ] && [ -n "$CLIENT_SECRET" ] && [ -n "$VCC_API_KEY" ]; then
    echo "🔒 Injecting obfuscated Volvo Developer credentials..."

    HISINGEN_GENERATED_CLIENT_ID="$CLIENT_ID" \
    HISINGEN_GENERATED_CLIENT_SECRET="$CLIENT_SECRET" \
    HISINGEN_GENERATED_VCC_API_KEY="$VCC_API_KEY" \
    HISINGEN_GENERATED_OUTPUT="$OUTPUT_SWIFT" \
    python3 - <<'PYTHON'
import os

client_id = os.environ["HISINGEN_GENERATED_CLIENT_ID"].strip()
client_secret = os.environ["HISINGEN_GENERATED_CLIENT_SECRET"].strip()
vcc_api_key = os.environ["HISINGEN_GENERATED_VCC_API_KEY"].strip()
output_path = os.environ["HISINGEN_GENERATED_OUTPUT"]

mask_key = 0x5C

def obfuscate(s):
    b = s.encode('utf-8')
    masked = [x ^ mask_key for x in b]
    return ', '.join(f"0x{x:02X}" for x in masked)

output = f"""// Generated by Scripts/inject-secrets.sh - DO NOT EDIT MANUALLY OR COMMIT REAL SECRETS
import Foundation

enum GeneratedVolvoSecrets {{
    static let isConfigured: Bool = true

    static var clientID: String {{
        let key: UInt8 = 0x{mask_key:02X}
        let bytes: [UInt8] = [{obfuscate(client_id)}]
        return String(bytes: bytes.map {{ $0 ^ key }}, encoding: .utf8) ?? ""
    }}

    static var clientSecret: String {{
        let key: UInt8 = 0x{mask_key:02X}
        let bytes: [UInt8] = [{obfuscate(client_secret)}]
        return String(bytes: bytes.map {{ $0 ^ key }}, encoding: .utf8) ?? ""
    }}

    static var vccApiKey: String {{
        let key: UInt8 = 0x{mask_key:02X}
        let bytes: [UInt8] = [{obfuscate(vcc_api_key)}]
        return String(bytes: bytes.map {{ $0 ^ key }}, encoding: .utf8) ?? ""
    }}
}}
"""

with open(output_path, "w", encoding="utf-8") as f:
    f.write(output)

print("✅ Obfuscated credentials generated into Sources/Hisingen/Services/API/GeneratedVolvoSecrets.swift")
PYTHON
else
    # Generate clean placeholder struct if no secrets provided
    cat <<EOF > "$OUTPUT_SWIFT"
// Default public fallback with no embedded secrets
import Foundation

enum GeneratedVolvoSecrets {
    static let isConfigured: Bool = false
    static var clientID: String { "" }
    static var clientSecret: String { "" }
    static var vccApiKey: String { "" }
}
EOF
    echo "ℹ️ No Volvo developer secrets found in environment or .env.secrets — using empty default template."
fi

DEFAULT_POLESTAR_IMAGE_API_KEY="da2-js63uvc7c5hwpdudt657d5lyou"
POLESTAR_IMAGE_API_KEY="${POLESTAR_IMAGE_API_KEY:-$DEFAULT_POLESTAR_IMAGE_API_KEY}"
POLESTAR_ACCOUNT_ID="${POLESTAR_ACCOUNT_ID:-}"
POLESTAR_CLIENT_ID="${POLESTAR_CLIENT_ID:-}"
POLESTAR_CLIENT_SECRET="${POLESTAR_CLIENT_SECRET:-}"

echo "🔒 Injecting obfuscated Polestar Developer Portal & render-CDN configuration..."

HISINGEN_GENERATED_POLESTAR_IMAGE_API_KEY="$POLESTAR_IMAGE_API_KEY" \
HISINGEN_GENERATED_POLESTAR_ACCOUNT_ID="$POLESTAR_ACCOUNT_ID" \
HISINGEN_GENERATED_POLESTAR_CLIENT_ID="$POLESTAR_CLIENT_ID" \
HISINGEN_GENERATED_POLESTAR_CLIENT_SECRET="$POLESTAR_CLIENT_SECRET" \
HISINGEN_GENERATED_POLESTAR_OUTPUT="$POLESTAR_OUTPUT_SWIFT" \
python3 - <<'PYTHON'
import os

image_api_key = os.environ.get("HISINGEN_GENERATED_POLESTAR_IMAGE_API_KEY", "").strip()
account_id = os.environ.get("HISINGEN_GENERATED_POLESTAR_ACCOUNT_ID", "").strip()
client_id = os.environ.get("HISINGEN_GENERATED_POLESTAR_CLIENT_ID", "").strip()
client_secret = os.environ.get("HISINGEN_GENERATED_POLESTAR_CLIENT_SECRET", "").strip()
output_path = os.environ["HISINGEN_GENERATED_POLESTAR_OUTPUT"]

mask_key = 0x5C

def obfuscate(s):
    b = s.encode('utf-8')
    masked = [x ^ mask_key for x in b]
    return ', '.join(f"0x{x:02X}" for x in masked)

def make_accessor(name, val):
    if not val:
        return f"    static var {name}: String {{ \"\" }}"
    return f"""    static var {name}: String {{
        let key: UInt8 = 0x{mask_key:02X}
        let bytes: [UInt8] = [{obfuscate(val)}]
        return String(bytes: bytes.map {{ $0 ^ key }}, encoding: .utf8) ?? ""
    }}"""

has_portal = "true" if (client_id and client_secret) else "false"
has_image = "true" if image_api_key else "false"

image_accessor = make_accessor("imageApiKey", image_api_key)
account_accessor = make_accessor("accountID", account_id)
client_accessor = make_accessor("clientID", client_id)
secret_accessor = make_accessor("clientSecret", client_secret)

output = f"""// Generated by Scripts/inject-secrets.sh - DO NOT EDIT MANUALLY OR COMMIT REAL SECRETS
import Foundation

enum GeneratedPolestarSecrets {{
    static let isConfigured: Bool = {has_image}
    static let hasDataPortalCredentials: Bool = {has_portal}

{image_accessor}

{account_accessor}

{client_accessor}

{secret_accessor}
}}
"""

with open(output_path, "w", encoding="utf-8") as f:
    f.write(output)

print("✅ Polestar credentials generated into Sources/Hisingen/Services/API/GeneratedPolestarSecrets.swift")
PYTHON

